name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # 让所有 run 步骤都在 smartseat-ml 目录内执行
    defaults:
      run:
        working-directory: smartseat-ml
    # 让 Python 能 import smartseat_ml 包
    env:
      PYTHONPATH: ${{ github.workspace }}/smartseat-ml
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          # 若有 requirements.txt 就按文件装；没有则装基础依赖
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest scikit-learn pandas numpy; fi

      - name: Run tests
        run: pytest -q tests

