name: Baseline CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add src to PYTHONPATH
        run: |
          echo "PYTHONPATH before: $PYTHONPATH"
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          echo "PYTHONPATH after: $PYTHONPATH"

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -q
