name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # 所有 run 步骤都在 smartseat-ml 目录执行
    defaults:
      run:
        working-directory: smartseat-ml

    # 让 Python 能 import smartseat_ml
    env:
      PYTHONPATH: ${{ github.workspace }}/smartseat-ml

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            # 打印一下文件内容，便于排查
            echo "=== requirements.txt ==="; cat requirements.txt || true
            pip install -r requirements.txt
          else
            pip install pytest scikit-learn pandas numpy
          fi
          python -c "import sys, pkgutil; print('pytest_installed=', bool(pkgutil.find_loader('pytest')))"

      - name: Run tests
        run: pytest -q tests
